name = "koharusaba"
author = "tokuyama"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a0695d14a5ddf89a0e60d72c5653504e8c16e80568256dc74e1d619dee1678a"

[versions]
fabric = "0.18.6"
minecraft = "1.19.2"
