name = "koharusaba"
author = "tokuyama"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bcaac216b3f76f9b175c50ab705fefe2312c3577484809c03a5ed3ea831c1f7"

[versions]
fabric = "0.18.6"
minecraft = "1.19.2"
